### PR TITLE
farcaster/wallet/peerd/swap: multiple node ids

### PR DESCRIPTION
**Pull request by zkao**

### CODE REVIEW

**Comment by zkao** [comment]
This enables maker to connect to several peers, and do swaps, but they all have to bind on different ports, on different listeners

**Comment by TheCharlatan** [comment]
Getting the following if `.peerd` does not exist yet:

```
[2021-12-10T23:55:47Z INFO  farcaster_node::config] Loading config file at: .data_dir_0/farcasterd.toml
[2021-12-10T23:55:47Z INFO  farcaster_node::farcasterd::runtime] farcasterd will attempt to fund automatically
[2021-12-10T23:55:47Z INFO  farcaster_node::service] New service farcasterd started
[2021-12-10T23:55:48Z INFO  farcaster_node::service] New service walletd started
[2021-12-10T23:55:48Z INFO  farcaster_node::farcasterd::runtime] Service walletd is now connected
thread 'main' panicked at 'Unable to create key file '.peerd/key'; please check that path exists', src/walletd/opts.rs:120:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Lederstrumpf** [comment]
> Getting the following if `.peerd` does not exist yet:
> 
> ```
> [2021-12-10T23:55:47Z INFO  farcaster_node::config] Loading config file at: .data_dir_0/farcasterd.toml
> [2021-12-10T23:55:47Z INFO  farcaster_node::farcasterd::runtime] farcasterd will attempt to fund automatically
> [2021-12-10T23:55:47Z INFO  farcaster_node::service] New service farcasterd started
> [2021-12-10T23:55:48Z INFO  farcaster_node::service] New service walletd started
> [2021-12-10T23:55:48Z INFO  farcaster_node::farcasterd::runtime] Service walletd is now connected
> thread 'main' panicked at 'Unable to create key file '.peerd/key'; please check that path exists', src/walletd/opts.rs:120:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

resolved via removal of dir nesting: https://github.com/farcaster-project/farcaster-node/pull/350/files#diff-8733d87aa8e718d82898c0321d56feada3e4fd1194ab636c8d2b8c7aac312622R1344

**Comment by zkao** [comment]
closes in favor #354

**Pull request closed without merging**
