### PR TITLE
Cancel publish6

### PR DESCRIPTION
**Pull request by zkao**

### CODE REVIEW

**Comment by TheCharlatan** [comment]
[failure_log.txt](https://github.com/farcaster-project/farcaster-node/files/7670629/failure_log.txt)

**Comment by TheCharlatan** [comment]
Something seems to have went wrong on the Bob refund path state transitions:
```
element: "State transition: BobState(Reveal) -> BobState(CoreArb)"
element: "Success: State transition: BobState(CoreArb) -> AliceState(Finish(Failure(Refunded)))"
```

```
DEBUG microservices::esb::controller] ESB request success(State transition: BobState(CoreArb) -> AliceState(Finish(Failure(Refunded)))) from swap<0xcd5b…ff51> forwarded to processing
```

**Comment by zkao** [comment]
a055728 teaches Bob to be a man ^^

**Review by TheCharlatan — APPROVED** [review]
Tested with #330

**Pull request merged**
