### PR TITLE
Update core to 0.4.0

### LINKED ISSUE #183: Format SwapId when running `swap-cli ls`
The SwapId is currently returned as:

```
swap_list(---
- - 110
  - 202
  - 178
  - 71
  - 171
  - 91
  - 126
  - 20
  - 114
  - 174
  - 82
  - 254
  - 207
  - 58
  - 155
  - 142
  - 201
  - 42
  - 94
  - 92
  - 27
  - 126
  - 135
  - 85
  - 145
  - 207
  - 73
  - 95
  - 57
  - 7
  - 151
  - 30
)
```

In the `info` call it is truncated: 
```
swaps:
  - "0x6eca…971e"
 ```
 
 And the `take` success message is also truncated:
```
Success: Public offer registered: 0x6010…30c4
 ```
If I'm not  mistaken the only way to retrieve a SwapId currently is by copying it from the logs. The SwapId should always be printed in full.

### PR DESCRIPTION
**Pull request by h4sh3d**
Fix #183 

Update monero to 0.16.0, remove strict encoding feature inside monero, apply manually strict encode and strict decode on custom struct with the help of farcaster consensus encoding and canonical bytes traits.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
I'm getting the following error on the taker side:
```
[2021-11-17T22:12:11Z INFO  farcaster_node::walletd::runtime] Loading Wallet::Bob
[2021-11-17T22:12:11Z INFO  farcaster_node::farcasterd::runtime] New instance of swapd launched with PID 19214
swapd: farcaster swap microservice
error: Invalid value for '<PUBLIC_OFFER>': Incorrect magic bytes
```

**Comment by h4sh3d** [comment]
> I'm getting the following error on the taker side:
> 
> ```
> [2021-11-17T22:12:11Z INFO  farcaster_node::walletd::runtime] Loading Wallet::Bob
> [2021-11-17T22:12:11Z INFO  farcaster_node::farcasterd::runtime] New instance of swapd launched with PID 19214
> swapd: farcaster swap microservice
> error: Invalid value for '<PUBLIC_OFFER>': Incorrect magic bytes
> ```

Do you have the serialized offer (the one in `doc` folder)? So I can see if I reproduce the bug

**Comment by TheCharlatan** [comment]
This is the offer I am running swap-cli take with:
```
swap1-cli take tb1quht074vsugyluwjj0cygheqldmhdxkpykp68vw 59fEswCxk6aF4KdxP1iw1XRN9pnMuFoHSUuFLgvkNMvEb1ct3sroVw91VMGWsBVRv3C6wdHeBQFdjJ4tthjcoYTo75oVc7d Offer:Cke4ftrP5A71LQM2fvVdFMNR4gmBqNCsR11111uMFuZTAsNgpdK8DiR11111TBJQ23113GTvtvqfD1111112g5B7VJxyP2bkaV6RgcZGAG7RkiZChNn5jMzwtV9EccsQLRFd11111111111111111111111111111111111111111AfZ113XSKLMz6q47
```

**Comment by h4sh3d** [comment]
The error has been fixed now, some `to_hex` functions has been replaced by `to_string` so the offer is transmitted between services in its full serialized version where `FromStr` can verify checksum and magic bytes correctly.

**Review by TheCharlatan — APPROVED** [review]
tACK

**Pull request merged**
