### PR TITLE
Swapd state management improvement

### PR DESCRIPTION
**Pull request by zkao**
Added many more state predicates at the level of the handling the requests

This allowed to remove a lot of the nesting

### CODE REVIEW

**Review by TheCharlatan — COMMENTED** [review]
Successfully tested some swaps. Did not try inverting the maker/taker roles yet though.

**Comment by zkao** [comment]
Inverting roles should not work yet

**Comment by zkao** [comment]
actually, just inverted the roles and swap works

so my little fixes fixed that too

**Comment by zkao** [comment]
I confirm Bob maker, Alice taker works on 419c81a as expected

**Review by TheCharlatan — APPROVED** [review]
Also swapped with inverted roles, just needs rebase and proper handling of unused code.

**Pull request merged**
