### PR TITLE
ci: update monerod and monero-wallet-rpc versions

### PR DESCRIPTION
**Pull request by LeoNero**

### CODE REVIEW

**Comment by h4sh3d** [comment]
I'm fine bumping these before #614, but check also for lws bump. I think ci will fail anyway.

Can you deactivate the lws test that fails in monero_syncer tests please?

**Comment by h4sh3d** [comment]
#627 should go first to fix the current versions in CI, then rebase and replace with your bump.

**Comment by LeoNero** [comment]
@h4sh3d should just wait for #614 or should still deactivate test on monero_syncer?

**Comment by h4sh3d** [comment]
> @h4sh3d should just wait for #614 or should still deactivate test on monero_syncer?

lws "should" work with tag `monerod-0.17.3.2` (what why I did #614), but doesn't work with 0.18 stack (at least not when I tried), so yes you can bump to 0.18 and deactivate lws so we can use the 0.18 without lws.

**Comment by LeoNero** [comment]
@h4sh3d done

**Comment by LeoNero** [comment]
@h4sh3d test ignored

**Comment by LeoNero** [comment]
Close since #614 already updates `monerod` and `monero-wallet-rpc`

**Pull request closed without merging**
