### PR TITLE
Move syncer declaration to farcaster-node

### PR DESCRIPTION
**Pull request by TheCharlatan**

### CODE REVIEW

**Comment by zkao** [comment]
It looks like the right thing to do, thanks. 

nonetheless its buggy. the indexes swapd creates are all positive and starting from 1

```
[2021-09-14T21:16:35Z ERROR farcaster_node::swapd::runtime] Transaction event received, unknow address with task id -1159943919 and txid a8f24ca6bcfae0887c05ed5dc54a9a31a570f47c8c2f8b136b83c82eedcff5c0
```

**Comment by TheCharlatan** [comment]
The error posted above was caused by code that I accidentally included while rebasing.
I also changed the task id's from i32 to u32 now. This should solve any future underflows as well.

**Comment by zkao** [comment]
didnt fix it, just made it postive :)

```
[2021-09-14T23:03:16Z ERROR farcaster_node::swapd::runtime] Transaction event received, unknow address with task id 3135023377 and txid ColoredString { input: "a8f24ca6bcfae0887c05ed5dc54a9a31a570f47c8c2f8b136b83c82eedcff5c0", fgcolor: Some(BrightYellow), bgcolor: None, style: Style(1) }
```

**Comment by zkao** [comment]
oh, i see, there is a regression there still where the keccak_256 is

**Comment by zkao** [comment]
lgtm, and basic testnet testing passed

**Pull request merged**
