### PR TITLE
Cli: Implement endpoint for listing funding addresses

### PR DESCRIPTION
**Pull request by TheCharlatan**

### CODE REVIEW

**Comment by h4sh3d** [comment]
Is there a simple way to add the swap id for each address, if yes this could be done in a follow up PR.

This would allow the GUI to re-conciliate the funding addresses with the swaps and display them together.

**Comment by TheCharlatan** [comment]
> Is there a simple way to add the swap id for each address, if yes this could be done in a follow up PR.

Yes, with https://github.com/farcaster-project/farcaster-node/pull/782 the data is in the database. I can add it in this PR, or in a follow however you prefer.

**Comment by h4sh3d** [comment]
> I can add it in this PR, or in a follow however you prefer.
Perfect! Then I suggest you add it in this one already, it'll be pretty easy to review everything at once

**Comment by TheCharlatan** [comment]
Ok, the swap id is now part of the returned information.

**Review by h4sh3d — APPROVED** [review]

**Pull request merged**
