### PR TITLE
Cleanly terminate swap on Cancel path: Refund and Punish

### PR DESCRIPTION
**Pull request by zkao**

### CODE REVIEW

**Comment by zkao** [comment]
closes #247

**Comment by TheCharlatan** [comment]
I'm seeing this after some time in the logs:
```
[2021-12-05T23:25:16Z WARN  farcaster_node::swapd::runtime] 0xe006…ecc5 | Be patient! Refund transaction with 21 confirmations evokes no response in state AliceState(RefundProcSigs)
```

How many confirmations do I have to wait until Alice does something?

**Comment by zkao** [comment]
> How many confirmations do I have to wait until Alice does something?

That message is not accurate. I added because I had no feeback of what was going on in the swap, after the log PR got merged.

Sweeping should happen at block that mines AccLock + 10

**Comment by zkao** [comment]
```
                            TxLabel::Refund
                                if self.state.swap_role() == SwapRole::Alice
                                    && !self.state.a_refund_seen()
                                    && self.syncer_state.tasks.script_pubkey.is_some()
```

**Comment by zkao** [comment]
you're probably not satisfying one of this predicates

**Comment by zkao** [comment]
or you already have seen refund, but the sweep is hanging on the syncer side?

**Comment by TheCharlatan** [comment]
Ah, I never fund Monero, so there is no AccLock transaction. In that case, Alice should just exit, once she sees cancel, right?

**Comment by zkao** [comment]
correct, good catch!

**Comment by zkao** [comment]
67e8071  should fix that

**Comment by TheCharlatan** [comment]
Which scenarios have you tested here? Are you terminating the bob swapd after the the two funding transactions are in?

**Comment by zkao** [comment]
I was racing the transactions, so my tests were random, but i always performed the funding on both sides

**Comment by zkao** [comment]
```                            TxLabel::Refund if self.state.swap_role() == SwapRole::Bob =>  ```

**Comment by zkao** [comment]
and for publishing the refund
```
                            TxLabel::Cancel
                                if self.temporal_safety.safe_refund(*confirmations)
                                    && (self.state.b_buy_sig() || self.state.b_core_arb())
                                    && self.txs.contains_key(&TxLabel::Refund) =>

```

**Comment by zkao** [comment]
> Which scenarios have you tested here? Are you terminating the bob swapd after the the two funding transactions are in?

It looks correct, and should refund without alice's participation

**Comment by Lederstrumpf** [comment]
We've been getting many failures on the functional tests [here](https://github.com/Lederstrumpf/farcaster-node/tree/refundFunctionalTest). @TheCharlatan mitigated a race condition addressed the issue for him on success path swaps, but I'm still getting failures there too (when fully rebased on this branch). Will continue debugging tomorrow.

I've reviewed most of the code here, but I'll only be confident once the functional tests pass consistently. But if this is blocking, we can merge and address the issues in a functional test PR.

**Comment by zkao** [comment]
@Lederstrumpf, its not blocking me.

just as a reminder, main is our development branch, not the release one, and in principle main doesnt even have to compile

**Comment by zkao** [comment]
@TheCharlatan @Lederstrumpf 

this is the PR im working on for the funding stuff on #278

im not sure (and wont check) #295 does all the stuff in the correct through the progress message. it might do, but that is not where this has been worked out.

**Comment by zkao** [comment]
the issue is reported on the code

```

    // Sleep here to work around a race condition between pending
    // SweepXmrAddress requests and tx Acc Lock confirmations. If Acc Lock
    // confirmations are produced before the pending request is queued, no
    // action will take place after this point.

```

**Comment by zkao** [comment]
this is the swapd code that is supposely buggy

```
                    Event::TransactionConfirmations(TransactionConfirmations {
                        confirmations: Some(confirmations),
                        ..
                    }) if self.state.b_buy_sig()
                        | (self.state.a_refundsig() && self.state.a_xmr_locked())
                        && *confirmations >= self.temporal_safety.sweep_monero_thr
                        && self.pending_requests.contains_key(&source) =>
                    {

```

**Comment by zkao** [comment]
my understanding is that if pending_requestst.contains_key(source) == false,  on the next AccLock update this should go

**Comment by zkao** [comment]
@Lederstrumpf @TheCharlatan 

can u please report both the state where failure happens?

**Comment by zkao** [comment]
the `|` should be `||`, but shouldnt affect here

**Comment by TheCharlatan** [comment]
It's just a problem of the tests, because no further confirmations are generated that trigger the pending requests to execute.

**Comment by zkao** [comment]
replaced by #317

**Pull request closed without merging**
