### PR TITLE
Syncer refactor

### PR DESCRIPTION
**Pull request by zkao**

### CODE REVIEW

**Comment by TheCharlatan** [comment]
I'm having trouble getting this to build with the latest farcaster core main branch. Does it also fix the broken syncer_state unit tests?

**Comment by zkao** [comment]
@TheCharlatan, with the Cargo.lock I added, it should compile

**Comment by zkao** [comment]
unit test find -> filter should be fixed, yes

**Comment by TheCharlatan** [comment]
The unit test is still broken, because the encoding is fucked up now with the address addendums. I see your frustration though, so lets merge this, to keep the train rolling. I will have the syncer types in the node by tonight, then we hopefully wont have any of this raw type encoding nonsense anymore.

**Comment by zkao** [comment]
The address subscription is still supported, but half-broken, as previously discussed, i just generalized a bit for allowing using the same code for both subscription or polling, the subscription being just a control gate on the middle to prevent unnecessary polling on no address change.

**Pull request merged**
