### PR TITLE
Bump dependencies for bitcoin 0.27 upgrade in core.

### PR DESCRIPTION
**Pull request by Lederstrumpf**
[bumped bitcoin to `0.27` in `farcaster-core`](https://github.com/farcaster-project/farcaster-core/pull/141) and these were the consequent changes (as well as some other consequent bumps in core: https://github.com/farcaster-project/farcaster-core/pull/148)

I think just about all of the lnp stack dependencies are now on the latest version (alpha/beta where necessary to be compatible with bitcoin 0.27) - quite little of the API has changed.

### CODE REVIEW

**Comment by zkao** [comment]
not sure its the best timing for this kind of upgrade, how should we proceed? it touches a lot of files

for my work which is now focused on swapd runtime it does not affect much

**Comment by zkao** [comment]
shall i rebase here?

**Comment by Lederstrumpf** [comment]
> shall i rebase here?

Yes - it's safe to do so, I believe. It does touch a lot of files, but the API changes are minimal - it's mostly a change of module hierarchies in lnp dependencies than anything else.

**Comment by zkao** [comment]
please fix the bugs related to this error message:

```[2021-09-29T13:59:10Z ERROR microservices::esb::controller] ESB request processing error: transport-level protocol error: the provided frame size (65815) exceeds frame size limit of MAX_FRAME_SIZE bytes```

**Comment by zkao** [comment]
steps to reproduce: alice makes an offer, bob takes it

**Comment by h4sh3d** [comment]
I added tests in core to see if protocol messages are able to encode/decode with strict encoding as expected and it seems to work. See https://github.com/farcaster-project/farcaster-core/pull/150.

The error might come from the dependencies update and how the node uses it.

**Comment by zkao** [comment]
since it was determined that there is no issue with the new upstream dependencies, but rather on our own code, I guess we can merge this. @Lederstrumpf push any new stuff, I do a final review, and we move on. I want to get my work included as well soon, next I will have to touch the wallet to retrieve a tx

**Comment by zkao** [comment]
@Lederstrumpf can we move forward with this one, it blocks merging further work?

**Comment by Lederstrumpf** [comment]
We can merge, but then it still crosses the message size limit. The changes needed to split the proof out from the parameters are quite significant. I should have them ready by tomorrow noon, if you wanna wait for those.

**Comment by zkao** [comment]
I will merge this anyway, then your new work goes in a new PR

**Pull request merged**
