### PR TITLE
Fee estimation

### PR DESCRIPTION
**Pull request by TheCharlatan**
Based on #388

@zkao , I am loosing quite some precision with the amount parsing. The reason I'm using the bitcoin amount type is that sending a float in the emitted Event is kind of hard to get right, since we can't hash floats. Do you want a string instead, that can then be parsed into a float?

### CODE REVIEW

**Comment by zkao** [comment]
@TheCharlatan we need at least 2 decimals (tx sizes on the order of >100vB, thus 0.01 sat/vB * 100 vB = 1 sat)

**Comment by zkao** [comment]
there was a bug in core that forced using sats for fees, though

but also theres some microsats unit or some other small unit, in rust-bitcoin

**Comment by TheCharlatan** [comment]
Funny that you mention, because I just saw that in rust-bitcoin. Would require us to upgrade farcaster-core first though :/

**Comment by TheCharlatan** [comment]
Actually, I think the precission is higher than you state here, since it is in kB.

**Comment by h4sh3d** [comment]
Core uses rust Bitcoin amount which can’t store less than a sat internally.

**Comment by TheCharlatan** [comment]
I think core should eventually use sat/kVByte as well.

**Comment by zkao** [comment]
that would work too, as we have more than enough precision

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zkao** [comment]
although i find that unit a bit counter intuitive, because txs are smaller than 1kB

**Review by zkao — APPROVED** [review]

**Review by zkao — APPROVED** [review]
what is the idea here:

- remove fee from offer and let syncer / swap / wallet pick the fee?
- just validate the fees?

**Comment by zkao** [comment]
@TheCharlatan

**Pull request merged**
