### PR TITLE
Core: update to version 0.6.2

### LINKED ISSUE #403: Remove fee management from surface
Fee will be managed by syncers. For now we remove the fee parameter, validation rules can be added later when their format is defined.

Closes #321.

### PR DESCRIPTION
**Pull request by h4sh3d**
Update core to version `0.6.2` and other dependencies.

Closes #403. Now the fee is only fixed and support fractional value such as 1.5 sat/vB with 1500 sat/kvB.

### CODE REVIEW

**Review by TheCharlatan — APPROVED** [review]
Changes look sane to me, but I'm not sure if everything is wired up correctly for the new unit.

**Comment by h4sh3d** [comment]
> Changes look sane to me, but I'm not sure if everything is wired up correctly for the new unit.

The fee strategy is passed directly to the functions that apply the fee, so it should be wired correctly.

**Comment by h4sh3d** [comment]
I can reproduce the grpc problem locally, I'll patch before we merge

**Review by TheCharlatan — APPROVED** [review]
Fix LGTM, you can merge once the CI is done.

**Pull request merged**
