### PR TITLE
Syncer TaskId

### PR DESCRIPTION
**Pull request by TheCharlatan**
This was more an exercise for myself than actually yielding much benefit. Especially the `SyncerBlockHeight` type is a bit unwieldy. Should I split their implementation into separate commits an PRs?

### CODE REVIEW

**Comment by zkao** [comment]
i rebased #207 here, and then we have issues with offer, format changed, it seems

**Comment by h4sh3d** [comment]
> i rebased #207 on #206 (on a private branch), and then we have issues with offer, format changed, it seems
> 
> alices: daemon:
> 
> ```
> [2021-11-20T15:27:38Z ERROR microservices::esb::controller] ESB request processing error: Farcaster core errors: Consensus error: Incorrect magic bytes
> ```

That’s probably an offer serialized with to_hex instead of to_string, at least the last 5 errors like this one were that for me.

**Comment by zkao** [comment]
ack

**Comment by h4sh3d** [comment]
`SyncerBlockHeight` is, as you said, not giving benefits. Maybe an implementation that generalized over different concept such as dags, or... I don't know what, but this is not needed now and maybe not even the right place to be generic, so I think you can drop the `SyncerBlockHeight` but keep the other one. (or discard both, I don't have a strong opinion)

**Comment by TheCharlatan** [comment]
I removed all the block height typing, just the TaskId remains.

**Review by h4sh3d — APPROVED** [review]

**Comment by TheCharlatan** [comment]
Do not merge before #230

**Comment by TheCharlatan** [comment]
Rebased, now that #230 is merged.

**Review by h4sh3d — APPROVED** [review]
utACK, but should not modify current behaviors

**Review by zkao — APPROVED** [review]
no brainer

**Pull request merged**
